### ISSUE TITLE
Feature request: reposition map on loading track file

### ISSUE THREAD

**Issue by oztourer** [marchyman/GeoTag#13]
It would be useful if the displayed map could automatically scroll and resize to display the track file when it is loaded. Alternatively, if the loaded track(s) could be shown in the left pane, clicking on a file could cause the map to be scaled and positioned to show that track.

**Comment by marchyman** [comment]
Thanks, that sounds like a good idea.  I'll look into it.

**Comment by marchyman** [comment]
The code to reposition the map when a track log is opened is in the repository.  It will be included on the next release.   Thanks again for the idea.

The code also fixes an issue with track logs with a timestamp that include milliseconds.   The log would display on the map but image updates would typically get the location of the last point of the first track segment instead of their proper location.
