### ISSUE TITLE
Error saving file

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#18]
Hello!
Thank u for this app!
One problem here 
Catalina 10.15.3 (19D76)
GeoTag from mac app store 4.8 (759)
backup folder is clean
file not locked
<img width="416" alt="Screen Shot 2020-03-22 at 12 37 10 AM" src="https://user-images.githubusercontent.com/56738034/77237015-45b64280-6bd5-11ea-9cac-8335406b0864.png">

**Comment by marchyman** [comment]
> One problem here
> Catalina 10.15.3 (19D76)
> GeoTag from mac app store 4.8 (759)

That error is sometimes caused when attempting tp update an image stored on a network drive.  It is often a transient error -- modifying the image and saving a second time works.

**Comment by anvme** [comment]
Problem in set coordinates 
console log  https://www.swisstransfer.com/d/ecfc5a80-8a52-433b-babf-6ddee5fa2648
I hide location with XX.XXXXX

**Comment by anvme** [comment]
I hope this log will help you.

**Comment by anvme** [comment]
It is very important 
<img width="190" alt="Screen Shot 2020-03-22 at 1 34 46 AM" src="https://user-images.githubusercontent.com/56738034/77237941-536fc600-6bdd-11ea-84be-2505b70dc2b0.png">

**Comment by marchyman** [comment]
What kind of image?  Raw file?  Jpeg? Are all images failing to update or only a certain few?

**Comment by anvme** [comment]
For now, the problem with jpeg
Only certain images I can't update.

**Comment by anvme** [comment]
Image for example - https://www.swisstransfer.com/d/7fa85d3c-4b1a-4674-b421-699c4879660f

**Comment by marchyman** [comment]
FYI: Saving a location update to that test image fails on my system, too.  Don't know why, yet.  Trying to see what is different from it compared to other jpeg images.

**Comment by anvme** [comment]
Sounds good, I hope  u will fix it

**Comment by marchyman** [comment]
The error is being reported by exiftool.  If I try to update the image using exiftool on the command line I get this error:

Warning: [minor] Entries in ExifIFD were out of sequence. Fixed. - IMAG4842_1.jpeg
Error: Error reading ThumbnailImage data in IFD1 - IMAG4842_1.jpeg

It looks like the exif has an offset and length for a thumbnail that does not exist.   There is a fix you can perform.  See this entry on the exiftool FAQ: https://exiftool.org/faq.html#Q20

Using the FAQ I did this:

`exiftool -all= -tagsfromfile @ -all:all -unsafe -icc_profile IMAG4842_1.jpeg`

which rebuilt the image metadata.  Exiftool, and by extension GeoTag, then had no problem updating the image.  I believe you can do this for all images in a directory by using the directory name instead of the image name in the command line.

**Comment by anvme** [comment]
Maybe we can implement this command to GeoTag? It will be useful, if GeoTag can't edit image metadata, it will execute this command and try again.
