### ISSUE TITLE
Unexpected Error - you don’t have permission to access “backup”.

### ISSUE THREAD

**Issue by anvme** [marchyman/GeoTag#24]
**Unexpected Error** 
Cannot copy /Users/username/Downloads/IMPORT/Canon EOS 600D/IMG_3328.jpeg to /Users/username/Downloads/backup/IMG_3328.jpeg

Reason: “IMG_3328.jpeg” couldn’t be copied because you don’t have permission to access “backup”.

Nothing was edit before the last successful edit.

**Comment by anvme** [comment]
After this error, I get next old error
**Error saving files**
One or more files could not be saved. Possible causes:
* The original file could not be backed up for unknown reasons
* ExifTool could not update the modified metadata

Error code: -1

**Comment by marchyman** [comment]
Please tell me about your system.   Which mac.  What kind of disk?  Are all your images on the internal disk or are you using external disks, too.  When you hit "save" how many images did you change that need updating?

I'm looking for anything that will give me a hint as to why you are having these issues when others are not.   It's hard to debug what I can not reproduce.

**Comment by anvme** [comment]
Internal disk only
Apple MacBook Pro 13-Inch "Core i5" 2.3 Mid-2017 Specs
Identifiers: Mid-2017 13" - MPXQ2LL/A* - MacBookPro14,1 - A1708 - 3164

**Comment by anvme** [comment]
>how many images did you change that need updating?
Just 1 image.

**Comment by marchyman** [comment]
Got it.  Thanks.

**Comment by marchyman** [comment]
GeoTag makes a request to macOS to copy the file.   The response from macOS says you don't have permissions to access the folder named /Users/username/Downloads/backup.  Can you select that folder in finder and do cmd-I?  I'm wondering what macOS thinks the read and write permissions may be.   Or if there is something special about the Downloads folder.

If the permissions are correct you can open GeoTag preferences and re-select the backup folder.

macOS is quite picky about giving programs access to files.   When you select a backup folder GeoTag creates a special kind of bookmark that is saved in program defaults.  Access to the folder can only be done through the special bookmark.  If, for example, you deleted the folder and then re-created it with the same name GeoTag would have to be given permission again.  macOS knows that the new folder isn't the same as the old folder.  I suspect either the folder changed or the special bookmark was otherwise invalidated.

**Comment by marchyman** [comment]
My guess is that the "bookmark" used to store the backup folder in system preferences became stale.  I was not always re-creating bookmarks when that happened.  If that was the issue it will be fixed in GeoTag5.  GeoTag5 will be released once I finish testing and documentation.
