### ISSUE TITLE
Allow disabling the backup function

### ISSUE THREAD

**Issue by enRGi** [marchyman/GeoTag#30]
When having an own backup system in place, the integrated backup function is rather inconvenient as it unnecessarily floods the hdd with more data/copies of the images.
This function should be made optional, so the user can decide for himself whether he wants to have backup copies or not.

**Comment by marchyman** [comment]
I will think on this.   I see your point, but also don't want to be the cause of someone losing a favorite image because they lost power at exactly the wrong instant.  I suppose that could be mitigated somewhat by defaulting to "use a backup" and adding an "are you sure" message if one chooses to turn the option off.

I'll update this issue once I make a decision.

**Comment by marchyman** [comment]
I added a no backup checkbox to program preferences.   The change is on github, but I've not yet made a new release.  Don't know when that will happen.
