### ISSUE TITLE
Daylight summer time option for the timezone

### ISSUE THREAD

**Issue by togarha** [marchyman/GeoTag#36]
Currently, only the timezone is selected, but the photos can have different times depending on the daylight summer time.
It would be interesting to have a checkbox to select the DST option or autodetect from the photos time, even though in this latest case, the different countries can have different DST dates, so it might be an improvement for the future.

**Comment by marchyman** [comment]
The timezone option is only needed to match a tracklog where the camera timestamp doesn't match the timestamp of the computer running GeoTag.  Yeah, that can happen if you forget to change the DST setting on your camera.  When computer and camera agree the timezone is not needed as it is selected according to the location and GPX timestamp of the image.  GPX timestamps are always GMT/UTC/Zulu time.

When I've forgotten to change camera settings my solution is to fix the images.  The image timestamps are incorrect, so I first make them correct.  Then they will match any track log.

**Comment by togarha** [comment]
Perhaps it's just a misunderstood on my side or a problem in my workflow, but that's how I work with photos:
- I have an Olympus OMD camera that stores the capture timestamp to the EXIF info, without timezone info, it just stores the local timezone into the capture timestamp (the time including the timezone, but without any UTC relationship).
- I have a GPS logger that stores all the positions related to the UTC time.
- I export the GPS logger data to a GPX format (all times in UTC).
- As the photos are in local time and GPX are in UTC, to match coordinates, the GeoTag TimeZone should be used to ensure the difference between local time and GPX time. This difference is different if the DST is enabled or not, or at least is different if you tried to match photos taken during DST a few months later without DST. I mean, if I'm trying to GeoTag photos in December that were taken in July. Then, the selected TimeZone would be different...

I don't know if my approach is wrong at any point, or if it makes sense to you...

Thanks,
Tomas

**Comment by marchyman** [comment]
Your computer knows its timezone.  GeoTag makes the assumption that camera timezone is the same as your computer.   This turns out to be correct for most of the people most of the time.   Go out in your local timezone.  Take pictures.  Use your tracker.  When you match images to the track log it just works.   It will also work if you go out of your local timezone without adjusting the camera time.  Of course if you do that the image time will not be correct for the place the image was taken.  But the track log will still match up.

When the camera timezone doesn't match the computer timezone an adjustment can be made.  It tells GeoTag that the camera was in a timezone +/- from the timezone of your computer.  That lets you set your camera time for the local area and still match tracklogs when you get home.  The feature to adjust timezones that way was added only a year ago.

**Comment by marchyman** [comment]
GeoTag5 (a branch that will turn into a release after more testing and updated doc) uses the TimeZone setting when updating the GPS timestamp.  The current version does not always do the right thing.  What is important isn't the actual time zone, but the time that your camera was set when you snapped the image.  Only the photographer knows that and it must be set manually unless it happens to match the computers current timezone.

**Comment by togarha** [comment]
Agree with your latest comment, thanks
