### ISSUE TITLE
Edit/Copy return always coordinates in dd.dddddd format even if settings is dd mm.mmmmm or dd° mm' ss.ss"

### ISSUE THREAD

**Issue by clwacker** [marchyman/GeoTag#41]
I have uploaded images in GeoTag which already have coordinates that I want to change.

I select one image and make Edit > Copy to first save the original coordinates but I see that the coordinates are in the format dd.dddddd even if the GeoTag settings is mm.mmmmm or dd° mm' ss.ss"

Would be nice to be able to copy the coordinates in the same format as selected in the GeoTag settings.
Thanks!

**Comment by marchyman** [comment]
I will add this to my to-do list.  5.2 fixes some minor coord formating issues, but copy still uses the underlying data which is a simple "double" value.  An issue is that conversion from/to may cause minor location differences due to rounding/truncation.  I don't know if such errors would be large enough to bother anyone.

**Comment by marchyman** [comment]
Code to use the current coordinate format when copying has been checked into the newmaps branch and will be part of the next release.
